server {
    listen 80;
    server_name waftext.linzefeng.top;

    limit_conn safeline_conn_per_ip 50;
    limit_req zone=safeline_req_per_ip burst=200 nodelay;

    location /safeline-static/ {
        alias /usr/local/openresty/nginx/lua/static/;
        expires 30d;
    }

    location /safeline-api/ {
        content_by_lua_block {
            require("captcha").handle()
        }
    }

    location = /pow {
        default_type text/html;
        content_by_lua_block {
            local pow = require "pow"
            ngx.header.content_type = "text/html; charset=utf-8"
            ngx.say(pow.get_pow_script())
        }
    }

    location /pow/ {
        content_by_lua_block {
            require("captcha").handle()
        }
    }

    access_by_lua_file /usr/local/openresty/nginx/lua/access.lua;
    header_filter_by_lua_file /usr/local/openresty/nginx/lua/header_filter.lua;
    body_filter_by_lua_file /usr/local/openresty/nginx/lua/body_filter.lua;

    location / {
        proxy_pass http://149.56.242.120:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }
}
  
